version: "3.8"

services:
  backend:
    build: .
    container_name: url-shortener-backend
    restart: always
    env_file: .env
    ports:
      - "6700:6700"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
