name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: suryathink/url-shortener-backend:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 instance's public IP or DNS
          username: ${{ secrets.EC2_USER }} # For example, "ec2-user" or "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }} # Your EC2 SSH private key (as a secret)
          port: 22
          script: |
            cd Advanced-URL-Shortener
            # Pull the latest Docker images (including the updated backend image)
            docker-compose pull
            # Restart containers in detached mode. The .env file on EC2 is used.
            docker-compose up -d
