name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: suryathink/url-shortener-backend:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 instance's public IP or DNS
          username: ${{ secrets.EC2_USER }} # For example, "ubuntu"
          key: ${{ secrets.EC2_KEY }} # Your EC2 SSH private key (as a secret)
          script: |
            sudo docker pull suryathink/url-shortener-backend:latest
            sudo docker stop url-shortener-backend || true
            sudo docker rm url-shortener-backend || true
            sudo docker run -d --name url-shortener-backend -p 6700:6700 suryathink/url-shortener-backend:latest
